-- MySQL Script generated by MySQL Workbench
-- Sat Jul 28 20:37:36 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema test
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `test` DEFAULT CHARACTER SET utf8mb4 ;
USE `test` ;

-- -----------------------------------------------------
-- Table `test`.`PROJECT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`PROJECT` (
  `PROJECT_ID` INT(10) ZEROFILL UNSIGNED NOT NULL AUTO_INCREMENT,
  `PROJECT_NM` VARCHAR(30) NOT NULL,
  `DEPT_ID` INT(10) UNSIGNED NOT NULL,
  `DIFFICULTY` CHAR(1) NULL,
  `INS_TM` DATETIME NOT NULL,
  `UPD_TM` VARCHAR(45) NOT NULL,
  `VERSION` INT(10) ZEROFILL UNSIGNED NOT NULL,
  PRIMARY KEY (`PROJECT_ID`),
  UNIQUE INDEX `PROJECTID_UNIQUE` (`PROJECT_ID` ASC),
  INDEX `PROJECT_NM` (`PROJECT_NM` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test`.`DEPT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`DEPT` (
  `DEPT_ID` INT(10) ZEROFILL UNSIGNED NOT NULL AUTO_INCREMENT,
  `DEPT_NM` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`DEPT_ID`))
ENGINE = InnoDB;

CREATE USER 'dbUser' IDENTIFIED BY 'hot2018!';

GRANT ALL ON `test`.* TO 'dbUser';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
